name: 'Build Package'
description: 'Build Python package with Poetry'
inputs:
  python-version:
    description: 'Python version'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup Python with Poetry
      uses: ./.github/actions/setup-python-poetry
      with:
        python-version: ${{ inputs.python-version }}

    - name: Build package
      shell: bash
      run: poetry build