name: 'Release Package'
description: 'Build and deploy package to PyPI or Test PyPI'
inputs:
  python-version:
    description: 'Python version'
    required: true
  environment:
    description: 'Release environment (test or prod)'
    required: true
    default: 'test'
  pypi-token:
    description: 'PyPI API token'
    required: true
  release-type:
    description: 'Type of GitHub release (release or prerelease)'
    required: false
    default: 'prerelease'
  release-name:
    description: 'GitHub release name'
    required: true
  release-body:
    description: 'GitHub release body'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Build package
      uses: ./.github/actions/build-package
      with:
        python-version: ${{ inputs.python-version }}

    - name: Deploy to Test PyPI
      if: inputs.environment == 'test'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ inputs.pypi-token }}
        repository-url: https://test.pypi.org/legacy/

    - name: Deploy to Production PyPI
      if: inputs.environment == 'prod'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ inputs.pypi-token }}

    - name: Create/Update GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/*
        name: ${{ inputs.release-name }}
        body: ${{ inputs.release-body }}
        draft: false
        prerelease: ${{ inputs.release-type == 'prerelease' }}