name: CICD Pipeline

on:
  push:
  workflow_dispatch:

jobs:
  get-python-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.python-version.outputs.version }}
      matrix: ${{ steps.python-version.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get Python version
        id: python-version
        uses: ./.github/actions/get-python-version

  lint-format-test:
    needs: get-python-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Setup Python with Poetry
        uses: ./.github/actions/setup-python-poetry
        with:
          python-version: ${{ needs.get-python-version.outputs.version }}

      - name: Run linter and formatter
        run: poetry run pre-commit run --all-files

      - name: Unit Tests with pytest
        run: poetry run pytest -v --durations=0 --cov --cov-report=xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Notify on failure
        if: failure()
        run: |
          echo "::error::Linting, formatting, or testing failed. Check logs for details."

  tag-release:
    needs: [lint-format-test, get-python-version]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Setup Python with Poetry
        uses: ./.github/actions/setup-python-poetry
        with:
          python-version: ${{ needs.get-python-version.outputs.version }}
          install-dependencies: 'false'

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(poetry version | cut -d' ' -f2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag already exists
        run: |
          git fetch --tags
          if git rev-parse "v${VERSION}" >/dev/null 2>&1; then
            echo "::error::Tag v${VERSION} already exists on GitHub. Please bump the version in pyproject.toml."
            exit 1
          fi

      - name: Create and push new tag
        run: |
          git tag -a "v${VERSION}" -m "Release version v${VERSION}"
          git push origin "v${VERSION}"

  publish-dev:
    needs: [lint-format-test, get-python-version]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python with Poetry
        uses: ./.github/actions/setup-python-poetry
        with:
          python-version: ${{ needs.get-python-version.outputs.version }}
          install-dependencies: 'false'

      - name: Build package
        shell: bash
        run: poetry build

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@v1.13.0
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          verbose: true

      - name: Notify on failure
        if: failure()
        run: |
          echo "::error::Publish failed. Check logs for details."

  publish-main:
    needs: [lint-format-test, get-python-version, tag-release]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: Check disk space
        run: df . -h

      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python with Poetry
        uses: ./.github/actions/setup-python-poetry
        with:
          python-version: ${{ needs.get-python-version.outputs.version }}
          install-dependencies: 'false'

      - name: Build package
        shell: bash
        run: poetry build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.13.0
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*
          name: Release v${{ needs.tag-release.outputs.version }}
          body: "Automated release for v${{ needs.tag-release.outputs.version }}"
          draft: false
          prerelease: false
          tag_name: v${{ needs.tag-release.outputs.version }}

      - name: Notify on failure
        if: failure()
        run: |
          echo "::error::Publish failed. Check logs for details."

  smoke-test:
    needs: [publish-main, tag-release, get-python-version]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python with Poetry
        uses: ./.github/actions/setup-python-poetry
        with:
          python-version: ${{ needs.get-python-version.outputs.version }}
          install-dependencies: 'false'

      - name: Wait for package availability
        run: |
          echo "Waiting 60 seconds for package to be available on PyPI..."
          sleep 60

      - name: Test prod package installation
        run: |
          pip install --index-url https://pypi.org/simple/ language-modeling-transformers==${{ needs.tag-release.outputs.version }}

      - name: Basic import test
        run: |
          python -c "import lmt; print('Package import successful')"

      - name: Notify on failure
        if: failure()
        run: |
          echo "::error::Smoke tests failed. Published package may have issues."
