name: CI
on:
  push:

jobs:
  get-python-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.python-version.outputs.version }}
      matrix: ${{ steps.python-version.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get Python version
        id: python-version
        uses: ./.github/actions/get-python-versions

  ruff-lint-and-format:
    needs: get-python-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python with Poetry
        uses: ./.github/actions/setup-python-poetry
        with:
          python-version: ${{ needs.get-python-version.outputs.version }}

      - name: Run tests
        run: poetry run pre-commit run --all-files

  pytest:
    runs-on: ubuntu-latest
    needs: [get-python-version, ruff-lint-and-format]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python with Poetry
        uses: ./.github/actions/setup-python-poetry
       with:
          python-version: ${{ needs.get-python-version.outputs.version }}

      - name: Run tests
        run: poetry run pytest -v --durations=0 --cov --cov-report=xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: [get-python-version, pytest]
    if: success()
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python with Poetry
        uses: ./.github/actions/setup-python-poetry

