name: Release Package to Test PyPI
permissions:
  contents: write
on:
  workflow_run:
    workflows: ["Create and Push Tag"]
    types: [completed]
    branches-ignore:
      - main

jobs:
  get-python-version:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      version: ${{ steps.python-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get Python version
        id: python-version
        uses: ./.github/actions/get-python-versions

  get-tag-version:
    runs-on: ubuntu-latest
    needs: get-python-version
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get version from tag
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

  publish-dev:
    runs-on: ubuntu-latest
    needs: [get-python-version, get-tag-version]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build package
        shell: bash
        run: poetry build

      - name: Publish to PyPI and GitHub
        uses: ./.github/actions/publish-package
        with:
          python-version: ${{ needs.get-python-version.outputs.version }}
          environment: test
          pypi-token: ${{ secrets.TEST_PYPI_API_TOKEN }}
          release-type: prerelease
          release-name: Release v${{ needs.get-tag-version.outputs.version }}
          release-body: "Automated release for v${{ needs.get-tag-version.outputs.version }}"